PracticaWeb/PracticaWeb/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PracticaWeb.Models
{
    public class Producto
    {
        public int Id  { get; set; }
        public string Nombre { get; set; }
        public int IdCategoria { get; set; }
    }
}

PracticaWeb/PracticaWeb/Controllers/CategoriaController.cs
using PracticaWeb.Clases;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaWeb.Controllers
{
    [Authorize]
    public class CategoriaController : Controller
    {
        private MetodosCategoria metodos = new MetodosCategoria();
        // GET: Categoria
        public ActionResult ListarCategoria()
        {
            var ListaCategorias = metodos.ObtenerCategorias();
            return View(ListaCategorias);
        }

        public ActionResult EditarCategoria(int IdCategoria)
        {
            var categoria = metodos.BuscarCategoria(IdCategoria);
            return View(categoria);
        }
        [HttpPost]
        public ActionResult EditarCategoriaAccion(int Id, string nombre)
        {
            metodos.EditarCategoria(Id,nombre);
          return RedirectToAction("ListarCategoria");
        }
        public ActionResult CrearCategoria()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult CrearCategoriaAccion(string NombreCategoria)
        {
            if (!string.IsNullOrEmpty(NombreCategoria))
            {
                metodos.AgregarCategoria(NombreCategoria);
            }

            return RedirectToAction("ListarCategoria");
        }

        public ActionResult EliminarCategoria(int IdCategoria)
        {
            metodos.EliminarCategoria(IdCategoria);
            return RedirectToAction("ListarCategoria");
        }

        public ActionResult FiltroCategoria(int IdCategoria)
        {
            var ListaProductos = metodos.ObtenerProductoPorCategori(IdCategoria);
            return View(ListaProductos);
        }
    }
}

PracticaWeb/PracticaWeb/Controllers/ProductoController.cs
using PracticaWeb.Clases;
using PracticaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaWeb.Controllers
{
    [Authorize]
    public class ProductoController : Controller
    {
        // GET: Producto
        private MetodosProducto metodos = new MetodosProducto();
        public ActionResult ListarProducto()
        {
            var VM = new VMProductoCategoria2();
            VM.ListaProductoCategoria= metodos.ObtenerProductos();
            var metodosCategoria = new MetodosCategoria();
            VM.ListaCategorias = metodosCategoria.ObtenerCategorias();
            return View(VM);
        }

        public ActionResult EditarProducto(int Id)
        {
            var metodoscategorias = new MetodosCategoria();
            VMProductoCategorias Vm = new VMProductoCategorias();
            Vm.producto = metodos.BuscarProducto(Id);
            Vm.categorias = metodoscategorias.ObtenerCategorias();
         
                 return View(Vm);
         
        }
        [HttpPost]
        public ActionResult EditarProductoAccion(Producto producto)
        {
            metodos.EditarProducto(producto);
            return RedirectToAction("ListarProducto");
        }
        public ActionResult CrearProducto(string mensaje="")
        {
            ViewBag.Mensaje = mensaje;

            var metodosCategoria = new MetodosCategoria();
            var ListaCategoria = metodosCategoria.ObtenerCategorias();
            return View(ListaCategoria);
        }
        [HttpPost]
        public ActionResult CrearProductoAccion(Producto producto)
        {
            if(producto.Nombre != "")
            {
                if(metodos.CrearProducto(producto.Nombre, producto.IdCategoria))
                {
                    return RedirectToAction("ListarProducto");
                }
                else { return RedirectToAction("CrearProducto", new { mensaje = "Problemas al crear el producto." });}              
            }
            else
            {
                return RedirectToAction("CrearProducto",new { mensaje="Los campos deben estar llenos."});
            }
           
        }
        public ActionResult EliminarProducto(int Id)
        {
            metodos.EliminarProducto(Id);
            return RedirectToAction("ListarProducto");
        }
    }
}

PracticaWeb/PracticaWeb/Views/Producto/CrearProducto.cshtml
@model List<PracticaWeb.Models.Categoria>
@{
    ViewBag.Title = "CrearProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if(!string.IsNullOrEmpty(ViewBag.mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.mensaje
        </div>
    }
<h2>Crear Producto</h2>

@using (Html.BeginForm("CrearProductoAccion", "Producto", FormMethod.Post))
{
    <div class="input-group">
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" required class="form-control" name="Nombre" />
        </div>
        <div class="form-group">
            <label>Categoria</label>
            <select class="form-control" required name="IdCategoria">
                @foreach (var item in Model)
                {
                    <option value="@item.Id">@item.NombreCategoria</option>
                }
            </select>
        </div>

        <button class="btn btn-primary" type="submit" >Crear</button>
    </div>
}

PracticaWeb/PracticaWeb/Views/Producto/EditarProducto.cshtml
@model PracticaWeb.Models.VMProductoCategorias

@{
    ViewBag.Title = "EditarProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Editar Producto</h2>

@using (Html.BeginForm("EditarProductoAccion", "Producto", FormMethod.Post))
{
    <div class="input-group">
        <input name="Id" hidden value="@Model.producto.Id" />
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" required class="form-control" value="@Model.producto.Nombre" name="Nombre" />
        </div>
        <div class="form-group">
            <label>Categoria</label>
            <select class="form-control" required name="IdCategoria">
                @foreach (var item in Model.categorias)
                {
                    <option value="@item.Id">@item.NombreCategoria</option>
                }
            </select>
        </div>
        <br />
        <button class="btn btn-primary" type="submit">Crear</button>
    </div>
}

PracticaWeb/PracticaWeb/Views/Producto/ListarProducto.cshtml
@model PracticaWeb.Models.VMProductoCategoria2
@{
    ViewBag.Title = "ListarProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListarProducto</h2>
<h3>@Html.ActionLink("Crear Producto", "CrearProducto")</h3>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-6">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Categoria</th>
                        <th>Accion1</th>
                        <th>Accion2</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListaProductoCategoria)
                    {
                        <tr>
                            <td>@item.Nombre</td>
                            <td>@item.NombreCategoria</td>
                            <td>
                                @using (Html.BeginForm("EditarProducto", "Producto"))
                                {
                                    <button type="submit" class="btn btn-success" name="Id" value="@item.Id">Editar</button>
                                }
                            </td>
                            <td>
                                @using (Html.BeginForm("EliminarProducto", "Producto"))
                                {
                                    <button type="submit" class="btn btn-danger" name="Id" value="@item.Id">Eliminar</button>
                                }
                            </td>

                        </tr>
                    }
                </tbody>

            </table>
        </div>
        <div class="col-lg-6 col-md-6">
            <h3>Filtrar productos por categoria.</h3>
            @using (Html.BeginForm("FiltroCategoria", "Categoria"))
            {
                <div class="form-group">
                    <label>Categoria</label>
                    <select class="form-control" name="IdCategoria">
                        @foreach (var item in Model.ListaCategorias)
                        {
                            <option value="@item.Id">@item.NombreCategoria</option>
                        }

                    </select>

                </div>
                <button type="submit" class="btn btn-primary" >Filtrar</button>
            }

        </div>

    </div>
</div>